auth-server: https://github.com/login
server:
  port: 8080
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: bd1c0a783ccdd1c9b9e4
      client-secret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      access-token-uri: ${auth-server}/oauth/access_token
      user-authorization-uri: ${auth-server}/oauth/authorize
      scope: user
    resource:
      user-info-uri: https://api.github.com/user
logging:
  level:
    org.springframework.security: DEBUG
spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat


