server:
  port: 8080
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: 746653690954-e97hg708dhbqb050nsl0obtfsh3ocktl.apps.googleusercontent.com
      client-secret: 355LU-Fj7s_IGrkq--hYRIX2
      access-token-uri: https://www.googleapis.com/oauth2/v3/token
      user-authorization-uri: https://accounts.google.com/o/oauth2/auth
      scope: profile,email
    resource:
      user-info-uri: https://www.googleapis.com/plus/v1/people/me
logging:
  level:
    org.springframework.security: DEBUG
spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat


